networks:
  dokploy-network:
    external: true

services:
  loki:
    image: grafana/grafana:latest
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki
    networks: [dokploy-network]
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.8
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [dokploy-network]
    restart: unless-stopped
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:2.6.1
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo.yml:/etc/tempo.yml:ro
      - tempo-data:/var/tempo
    networks: [dokploy-network]
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.2.0
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=change-me
      - GF_SERVER_ROOT_URL=https://graf.nutline.dev
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_SERVER_DOMAIN=graf.nutline.dev
      - GF_SERVER_ENFORCE_DOMAIN=true
    volumes:
      - grafana-data:/var/lib/grafana
    networks: [dokploy-network]
    restart: unless-stopped
    depends_on:
      - loki
      - tempo

volumes:
  loki-data:
  tempo-data:
  grafana-data: